### ISSUE TITLE
Add a LICENSE

### ISSUE THREAD

**Issue by ricardoboss** [trenz-gmbh/trenz-docs#27]
To enable others to freely use, redistribute and/or modify this software for their own needs, we need a license file, which regulates how the source code can be used.

I think the conditions should allow modifying the code and then redistributing it, even as closed source. Private and commercial use should be allowed too. The license should also protect us from being held liable for any damages that may occur.

Some candidates include:

- [`Apache-2.0`](https://choosealicense.com/licenses/apache-2.0/)
- [`MIT`](https://choosealicense.com/licenses/mit/)
- [`BSD 2-Clause`](https://choosealicense.com/licenses/bsd-2-clause/)/[`BSD 3-Clause`](https://choosealicense.com/licenses/bsd-3-clause/)
- maybe even the [`Unlicense`](https://choosealicense.com/licenses/unlicense/)?

The GPL license would also be nice, but they would require to disclose the source code of the derived work, which some users may not want or would prevent them from using this software altogether.

These are some of the resources I used to research these licenses, so you can look for yourselves:

- https://choosealicense.com/
- https://tldrlegal.com/
- https://medium.com/nationwide-technology/a-short-guide-to-open-source-licenses-cf5b1c329edd

**Comment by chucker** [comment]
Unlicense is not an option in Germany.

> The GPL license would also be nice, but they would require to disclose the source code of the derived work, which some users may not want or would prevent them from using this software altogether.

That's only relevant for redistribution, unless you use AGPL. GPL (without A) would still let companies **run** wikis with customizations that they don't share, just not redistribute those as their own piece of software without adhering to the GPL.

Regardless, I'd stick to MIT.
